services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    volumes:
      # Для production с реальным доменом раскомментируйте эти строки:
      - ./ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      # Теперь фронтенд будет обращаться к API через nginx
      - NEXT_PUBLIC_BACKEND_URL=https://justcreatedsite.ru/api
    restart: unless-stopped
    expose:
      - "4000"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3500
    restart: unless-stopped
    expose:
      - "3500"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  nginx_logs: