version: '3.9'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:4000"
    environment:
      - NODE_ENV=production
      # ВАЖНО: без nginx фронтенд должен ходить прямо на порт бэкенда
      - NEXT_PUBLIC_BACKEND_URL=http://YOUR_SERVER_IP:3500/api
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3500:3500"
    environment:
      - NODE_ENV=production
      - PORT=3500
    restart: unless-stopped