version: '3.9'
services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 4000:4000
    environment:
      - NODE_ENV=development
      - BACKEND_URL=http://localhost:3500/api
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:3500/api


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3500:3500
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

